// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZzpLZVVDeIRsxSSq5hIDaftmZ-d_0ZR8',
    appId: '1:148770898938:web:46a4ead01baa58cd1d1a43',
    messagingSenderId: '148770898938',
    projectId: 'groceryapp-cbd7f',
    authDomain: 'groceryapp-cbd7f.firebaseapp.com',
    storageBucket: 'groceryapp-cbd7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNv3-vM065Y1MxTzyBQRqufHSFRAmQr7M',
    appId: '1:148770898938:android:b4a68b11ee1bb3081d1a43',
    messagingSenderId: '148770898938',
    projectId: 'groceryapp-cbd7f',
    storageBucket: 'groceryapp-cbd7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtZlNJWfK2N-DkD5EhEZKuXEBXQlgCew',
    appId: '1:148770898938:ios:a680ccc41dac5e111d1a43',
    messagingSenderId: '148770898938',
    projectId: 'groceryapp-cbd7f',
    storageBucket: 'groceryapp-cbd7f.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABtZlNJWfK2N-DkD5EhEZKuXEBXQlgCew',
    appId: '1:148770898938:ios:a680ccc41dac5e111d1a43',
    messagingSenderId: '148770898938',
    projectId: 'groceryapp-cbd7f',
    storageBucket: 'groceryapp-cbd7f.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZzpLZVVDeIRsxSSq5hIDaftmZ-d_0ZR8',
    appId: '1:148770898938:web:9149baf91c73d8a41d1a43',
    messagingSenderId: '148770898938',
    projectId: 'groceryapp-cbd7f',
    authDomain: 'groceryapp-cbd7f.firebaseapp.com',
    storageBucket: 'groceryapp-cbd7f.firebasestorage.app',
  );
}
